spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8000
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    ampler:
      probability: 1.0
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
management:
  zipkin:
    tracing:
      read-timeout: 60
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,env,health,prometheus
  tracing:
    sampling:
      probability: 1