spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Sidhu@1424
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      exclude: public/**
      poll-interval: 2s
      quiet-period: 1s
  sql:
    init:
      continue-on-error: false
server:
  port: 8090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: http://localhost:8761/eureka  
security.jwt.secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time: 3600000
