spring:
  application:
    name: customerservice
  config:
    import: optional:configserver:http://localhost:8000
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    # MyQSL
    url: jdbc:mysql://localhost:3306/customer_service_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Sidhu@1424
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update 
    # Oracle settings
    #url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    #username: CO
    #password: admin
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    
server:
  port: 9030
management:
    endpoints:
      web:
        exposure:
          include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: http://localhost:8761/eureka            