spring:
  application:
    name: productservice
  config:
    import: optional:configserver:http://localhost:8000
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
    # MyQSL
    url: jdbc:mysql://localhost:3306/product_service_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Sidhu@1424
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    ampler:
      probability: 1.0
    # Oracle settings
    #url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    #username: CO
    #password: admin
    #driver-class-name: oracle.jdbc.driver.OracleDriver
server:
  port: 9010
management:
  zipkin:
    tracing:
      read-timeout: 60
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,env,health,prometheus
  tracing:
    sampling:
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: http://localhost:8761/eureka          
