spring:
  application:
    name: configserver
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: file:///D://DEV//GitHub//git-cloud-config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8000
management:
  endpoints:
    web:
      exposure:
        include: "*"
  